[package]
name = "oxidizy"
version = "0.4.0"
authors = ["selfup <boudinot.regis@yahoo.com>"]
edition = "2024"

[dependencies]
unigen = { git = "https://github.com/selfup/unigen-rs", version = "0.4.0", default-features = false }

bevy = "0.15.3"
