[package]
name = "oxidizy"
version = "0.1.1"
authors = ["selfup <boudinot.regis@yahoo.com>"]
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
unigen = { path = "crates/unigen", version = "0.1.0", default-features = false }

rand = "0.8.4"
bevy = "0.6.0"
