[package]
name = "oxidizy"
version = "0.3.0"
authors = ["selfup <boudinot.regis@yahoo.com>"]
edition = "2024"

[workspace]
members = ["crates/*"]

[dependencies]
unigen = { path = "crates/unigen", version = "0.3.0", default-features = false }

bevy = "0.15.3"
