[package]
name = "oxidizy"
version = "0.4.3"
authors = ["selfup <boudinot.regis@yahoo.com>"]
edition = "2024"

[dependencies]
unigen = { git = "https://github.com/selfup/unigen-rs", version = "0.4.4", default-features = false }

bevy = "0.19.1"
bytemuck = { version = "1.25.2", features = ["derive"] }
rayon = "1.12.0"
